export const youtube = 'https://www.youtube.com/@rodrigoteranhdz'
export const blog = 'https://medium.com/@rodrigoteranhdz'
export const github = 'https://github.com/RodrigoTeran'
export const linkedin = 'https://www.linkedin.com/in/rodrigoteranhdz'
export const instagram = 'https://www.instagram.com/rodrigoteranhdz'
export const neojaus = 'https://neojaus.com'
